{% set name = "piq" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/photosynthesis-team/piq/archive/v{{ version }}.tar.gz
  sha256: beab5678dc0085cd473a23c57d3503aac3f985b344cc8ec7c21d62beda5ee446

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pytorch >=1.5.1
    - torchvision >=0.6.1
    - scipy >=1.3.3
    - gudhi >=3.2
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch >=1.5.1
    - torchvision >=0.6.1
    - scipy >=1.3.3
    - gudhi >=3.2

test:
  imports:
    - piq
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/photosynthesis-team/piq
  summary: PyTorch Image Quality (PIQ)
  description: |
    PyTorch Image Quality (PIQ) is a collection of measures and metrics for
    image quality assessment. PIQ helps you to concentrate on your experiments
    without the boilerplate code. The library contains a set of measures and
    metrics that is continually getting extended. For measures/metrics that can
    be used as loss functions, corresponding PyTorch modules are implemented.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
